import { Component, inject, PLATFORM_ID, signal, OnInit } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';

// Import services
import { SeoService } from '../../../../shared/services/seo.service';

// Import components
import { Hero } from '../../components/hero/hero';
import { WebsiteShowcase } from '../../components/website-showcase/website-showcase';
import { VideoTrailer } from '../../components/video-trailer/video-trailer';
import { LogosShowcase } from '../../components/logos-showcase/logos-showcase';
import { BrandCharter } from '../../components/brand-charter/brand-charter';
import { BusinessPlan } from '../../components/business-plan/business-plan';
import { Diagrams } from '../../components/diagrams/diagrams';
import { DeploymentScreenshots } from '../../components/deployment-screenshots/deployment-screenshots';
import { CtaSection } from '../../components/cta-section/cta-section';
import { Cta } from '../../components/cta/cta';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [
    CommonModule,
    Hero,
    WebsiteShowcase,
    VideoTrailer,
    LogosShowcase,
    BrandCharter,
    BusinessPlan,
    Diagrams,
    DeploymentScreenshots,
    CtaSection,
    Cta,
  ],
  templateUrl: './home.html',
  styleUrl: './home.css',
})
export class Home implements OnInit {
  // Angular-initialized properties
  protected readonly isBrowser = signal(isPlatformBrowser(inject(PLATFORM_ID)));
  private readonly seoService = inject(SeoService);

  // State properties

  // Lifecycle methods
  ngOnInit(): void {
    this.setupSeo();
  }

  // SEO setup
  private setupSeo(): void {
    const title =
      'Idem: AI-Powered Logo, Brand, Business Plan & App builder & Deployment Generator';
    const description =
      "Transform your ideas into live applications with Idem's AI platform. Create professional brands, generate business plans, build UML diagrams, and deploy apps instantly. From concept to production in minutes.";

    const metaTags = [
      { name: 'description', content: description },
      {
        name: 'keywords',
        content:
          'AI brand creation, instant app deployment, AI assistant, business plan generator, UML diagram creator, logo design AI, website builder, brand identity, technical architecture, one-click deployment, SaaS platform, startup tools, AI automation, digital transformation, app development, brand design, visual identity, deployment automation, AI-powered development',
      },
      { name: 'author', content: 'Idem Team' },
      { name: 'robots', content: 'index, follow' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'theme-color', content: '#6366f1' },
      { name: 'application-name', content: 'Idem' },
      { name: 'apple-mobile-web-app-title', content: 'Idem' },
      { name: 'apple-mobile-web-app-capable', content: 'yes' },
      { name: 'apple-mobile-web-app-status-bar-style', content: 'default' },
      { name: 'msapplication-TileColor', content: '#6366f1' },
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:site', content: '@IdemAfrica' },
      { name: 'twitter:creator', content: '@IdemAfrica' },
    ];

    const ogTags = [
      { property: 'og:title', content: title },
      {
        property: 'og:description',
        content:
          'Revolutionary AI platform that builds your brand, creates business plans, technical specs, and deploys applications instantly. Professional logos, business plans, UML diagrams, and live apps - all generated by AI in minutes.',
      },
      { property: 'og:type', content: 'website' },
      { property: 'og:url', content: this.seoService.domain },
      { property: 'og:site_name', content: 'Idem' },
      { property: 'og:locale', content: 'en_US' },
      {
        property: 'og:image',
        content: `${this.seoService.domain}/assets/seo/og-image.jpg`,
      },
      { property: 'og:image:width', content: '1200' },
      { property: 'og:image:height', content: '630' },
      { property: 'og:image:type', content: 'image/jpeg' },
      {
        property: 'og:image:alt',
        content: 'Idem - AI-Powered Brand Creation & App Deployment Platform',
      },
    ];

    this.seoService.updateTitle(title);
    this.seoService.updateMetaTags(metaTags);
    this.seoService.updateOgTags(ogTags);
    this.seoService.setCanonicalUrl('/');

    // Add structured data for the main website
    this.addStructuredData();
  }

  private addStructuredData(): void {
    if (!this.isBrowser()) return;

    const structuredData = {
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Idem',
      description:
        'AI-powered platform for brand creation and instant app deployment. Create professional brands, business plans, UML diagrams, and deploy applications seamlessly.',
      url: this.seoService.domain,
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web Browser',
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD',
        availability: 'https://schema.org/InStock',
        description: 'Free tier available with premium features',
      },
      creator: {
        '@type': 'Organization',
        name: 'Idem',
        url: this.seoService.domain,
        logo: `${this.seoService.domain}/assets/images/logo.png`,
        sameAs: [
          'https://twitter.com/IdemAfrica',
          'https://linkedin.com/company/idem-africa',
        ],
      },
      featureList: [
        'AI Brand Creation',
        'Logo Design Generation',
        'Business Plan Creation',
        'UML Diagram Generation',
        'Website Building',
        'Instant App Deployment',
        'Technical Architecture Design',
        'Brand Identity Development',
      ],
      screenshot: `${this.seoService.domain}/assets/images/app-screenshot.jpg`,
      aggregateRating: {
        '@type': 'AggregateRating',
        ratingValue: '4.8',
        ratingCount: '150',
        bestRating: '5',
        worstRating: '1',
      },
    };

    // Check if structured data already exists
    const existingScript = document.querySelector(
      'script[data-home-structured-data]'
    );
    if (existingScript) {
      return;
    }

    const script = document.createElement('script');
    script.type = 'application/ld+json';
    script.setAttribute('data-home-structured-data', 'true');
    script.textContent = JSON.stringify(structuredData);
    document.head.appendChild(script);
  }
}
