name: CI/CD IDEM FRONTEND

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🔧 Build Docker image on remote server
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ steps.vars.outputs.commit_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short commit ID
        id: vars
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: SSH Build Image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Idem-app/idem
            export IMAGE_NAME=ghcr.io/idem-ia/idem:${{ steps.vars.outputs.commit_id }}
            echo "🔨 Build Docker image $IMAGE_NAME"
            docker build -t $IMAGE_NAME .

  push:
    name: 📤 Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Push Image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Idem-app/idem
            export IMAGE_NAME=ghcr.io/idem-ia/idem:${{ needs.build.outputs.commit_id }}

            echo "📤 Push Docker image $IMAGE_NAME"
            docker push $IMAGE_NAME

  deploy:
    name: 🚀 Deploy with docker-compose
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Idem-app/idem
            export IMAGE_NAME=ghcr.io/idem-ia/idem:${{ needs.push.needs.build.outputs.commit_id }}
            echo "🔁 Update docker-compose with new image tag"
            sed -i "s|image: ghcr.io/.*/idem:.*|image: $IMAGE_NAME|" docker-compose.yml

            echo "♻️ Restarting docker-compose"
            docker-compose down && docker-compose up -d
